### ISSUE TITLE
[BUG] Dropdown menu, connect and record ATIS buttons not showing up

### ISSUE THREAD

**Issue by SpyrosTTK** [vatis-project/vatis#10]
I can not connect the ATIS, or choose the preset profiles because the buttons are not showing up
![image](https://user-images.githubusercontent.com/79931000/163969612-e03a0c00-3cda-45c8-8737-77fe63450c62.png)
And the standard should be this
![image](https://user-images.githubusercontent.com/79931000/163969717-68f7e785-a34e-403a-a329-ab80711fba95.png)
Using Windows 11

**Comment by SpyrosTTK** [comment]
Issue fixed after changing high DPI settings ->> Enabled High DPI scaling override. Scaling performed by System or System(Enhanced) (both work)
![image](https://user-images.githubusercontent.com/79931000/164154048-635072ab-3bf0-44bf-a4a0-4caa12bd121a.png)

**Comment by davidoskay** [comment]
110% scaling, this workaround doesn't work
