### ISSUE TITLE
Append "meters/kilometers" does not append to visibility

### ISSUE THREAD

**Issue by trismann** [vatis-project/vatis#113]
Using beta 7 this option seems to no longer at "meters" or "kilometers" to the visibility in the voice ATIS using non-FAA formatting.

**Comment by justinshannon** [comment]
I can't reproduce this. In my testing, `EGLL 260320Z AUTO 16003KT 3000 -RA FEW017/// BKN036/// //////CB 08/07 Q1000` yields "VISIBILITY THREE THOUSAND METERS" in the voice ATIS.

What airport are you using this with? Do you have a METAR report that I can try debugging this with?

**Comment by trismann** [comment]
Currently testing with CYYZ. `METAR CYYZ 260300Z 23020G29KT 15SM −RA OVC020 03/01 A2947`
In previous versions, I believe this setting would enable the "METERS" at the end of the visibility even with it in SM. I could then add a contraction as my goal is for the voice atis to read "VISIBILITY ONE FIVE MILES".

**Comment by justinshannon** [comment]
You’ll be able to customize this once the ATIS formatting feature is implemented (see #73).

**Comment by justinshannon** [comment]
Beta 8 is now available with support for customizing the ATIS format; see the updated documentation for details: https://docs.vatis.clowd.io/#/client?id=formatting
