### ISSUE TITLE
FULL_WX_STRING leaves no spaces between METAR items

### ISSUE THREAD

**Issue by mythicfci** [vatis-project/vatis#115]
With vATIS 4.0 beta 7, the pauses between METAR items in FULL_WX_STRING seem to be missing - the voice ATIS is now pronouncing all of the weather items as one long run-on sentence. See [this recording](https://drive.google.com/file/d/14Vhh79sf2nDMJ7AFHWREUyP3rLszdDCD/view?usp=sharing) for an example.

The syntax used in the excerpt is: `WEATHER AT [OBS_TIME] UTC. [FULL_WX_STRING] HPA, [PRESSURE_INHG] INHG.` (with the aliases HPA = Hectopascals and INHG = Inches).

**Comment by justinshannon** [comment]
I didn't notice this during my testing; let me know if you're still experiencing this with beta 8.

**Comment by justinshannon** [comment]
I'm going to close this out. If you're still experiencing this issue, please open a new bug report issue.
