### ISSUE TITLE
[Feature] Metric support

### ISSUE THREAD

**Issue by RudiZhang** [vatis-project/vatis#12]
Is it possible to add an option to enable metric units. Convert wind speed and cloud to meters？

**Comment by justinshannon** [comment]
Is the METAR not encoded in the metric format? Can you provide an example station/METAR?

**Comment by RudiZhang** [comment]
@justinshannon Indeed, In China METAR clouds will be in feet, but in D-ATIS and voice they are automatically converted to metres in 10. For example FEW030 would be decoded as Few Cloud Ceiling 900 meters

**Comment by justinshannon** [comment]
Can you clarify the wind speed conversion? I see that many Chinese stations already report the wind in MPS. Are you referring to stations that are reporting the wind in KTS and you want to convert those to MPS?

With regards to the cloud height conversion, when is the value rounded up or down? In your example, 3000ft converts to 914.4 meters, but reported as 900.

**Comment by RudiZhang** [comment]
@justinshannon for wind speed are ok. if it shows MPS then MPS. For cloud will use feet altitude * 0.3 then will come a metric cloud value

**Comment by justinshannon** [comment]
An option to convert cloud heights to meters will be available in the next version.

**Comment by RudiZhang** [comment]
I just found out that the cloud doesn't seem to change to metric?

![image](https://user-images.githubusercontent.com/40914896/184373468-f5fdf853-0642-4f23-ad8a-c40e8b9dce82.png)
![image](https://user-images.githubusercontent.com/40914896/184373523-ef92d0e2-3231-4208-a3cc-611833167954.png)
