### ISSUE TITLE
Initial atis code range letter is not being saved

### ISSUE THREAD

**Issue by itayfish** [vatis-project/vatis#121]
The Departure ATIS code range is set from N to Z.
I tried setting the Arrival ATIS code range from A to M (clicked Apply then OK) but it wouldn't save.
The Initial letter in the range can be saved but the last letter in the range can't.
This issue occurs in both Departure and Arrival ATIS.

**Comment by justinshannon** [comment]
This is fixed in https://github.com/vatis-project/vatis/pull/114 which will included in the next release. I’m still finishing up the documentation since there is a lot of functionality changes associated with custom ATIS formatting in the next release.
