### ISSUE TITLE
Separating winds

### ISSUE THREAD

**Issue by Alep9841** [vatis-project/vatis#123]
Hello guys, i have noticed that by using the wind command, the atis will say "Wind XX/XXX", I'd like to have a command where it only reads the value of the wind at that moment, so instad of saying "Wind XX/XX", It'd say "XX/XX". That is because I would like the departure atis to say "Wind Stop-End ZZ/ZZ" and the arrival atis to say "Wind Touch Down YY/YY".  I know we only have 1 value for winds atm but i would like to have it like that for added immersion. Would this be possible? Thank you

**Comment by justinshannon** [comment]
This should be possible in the next version, see my comment on this issue for high-level details: https://github.com/vatis-project/vatis/issues/73#issuecomment-1489630243.

My goal is to get this released later this week.

**Comment by justinshannon** [comment]
Beta 8 is available, which implements the new custom ATIS formatting. See the updated documentation for details on how to customize your ATIS format: https://docs.vatis.clowd.io/#/client?id=formatting
