### ISSUE TITLE
File write errors when updating to B8 / Installer Check for Active instance

### ISSUE THREAD

**Issue by ml0130** [vatis-project/vatis#124]
This was only about half of the files that it was throwing errors with
![image](https://user-images.githubusercontent.com/27445711/232958125-4015b461-5435-40b1-b9f7-f43579904ef5.png)
![image](https://user-images.githubusercontent.com/27445711/232958162-f956de2a-c0ad-4437-b04b-7df78b8d018e.png)
![image](https://user-images.githubusercontent.com/27445711/232958203-6c0fef3c-22e2-4750-8120-13f68019e243.png)
![image](https://user-images.githubusercontent.com/27445711/232958237-dfbe6b9e-a1f4-4897-93e0-2a539c3faea0.png)
![image](https://user-images.githubusercontent.com/27445711/232958263-4d3b4eda-fe94-42fc-b08b-e6b62263651f.png)
![image](https://user-images.githubusercontent.com/27445711/232958293-a8cea8fe-2661-43e1-880e-ccfdaac3b3c6.png)
![image](https://user-images.githubusercontent.com/27445711/232958332-055c96bd-911e-4ac9-9eb0-4543c6fa4487.png)
![image](https://user-images.githubusercontent.com/27445711/232958361-b30d6741-9366-4f06-8ff2-308a106ddcd5.png)
![image](https://user-images.githubusercontent.com/27445711/232958395-5596477f-6555-4243-9c44-351e62ce33ad.png)
![image](https://user-images.githubusercontent.com/27445711/232958424-caf95608-764e-4954-a247-6a78601bec3f.png)
![image](https://user-images.githubusercontent.com/27445711/232958461-3a9e0bc8-ae08-487a-910c-85ba1c44c094.png)
![image](https://user-images.githubusercontent.com/27445711/232958493-d63f98cc-32a8-4ab7-baa7-bf8edd1a3948.png)
![image](https://user-images.githubusercontent.com/27445711/232958521-c31efcfe-6c92-4f99-b2a2-f235a0b0fa63.png)
![image](https://user-images.githubusercontent.com/27445711/232958569-d9281237-89cb-4252-babb-628bcf7ad0aa.png)
![image](https://user-images.githubusercontent.com/27445711/232958621-aa87470a-2747-4d5f-8912-82a8db5c7557.png)

**Comment by ml0130** [comment]
So found what the issue was seems like there was a lingering instance of vatis running in the task manager, and the installer didn't seem to catch that the instance was being held as an active/running program. May I suggest a check is added to the installer to look to see if any vatis instance is running before it trys to update any files

**Comment by justinshannon** [comment]
This should be fixed for future updates. You may get this error when you update to beta 9, but it should be resolved when updating to future versions.
