### ISSUE TITLE
vATIS is stuck in a download loop trying to download beta10

### ISSUE THREAD

**Issue by neilenns** [vatis-project/vatis#127]
Ran vatis this morning and it tried to download beta 10. It keeps:

1. Downloading to 100%
2. Playing a beep sound
3. Sometimes an error dialog flashes briefly
4. Go back to step 1

It's been doing this for a solid 5 minutes now. I can't catch it fast enough in Task Manager to kill it either.

**Comment by justinshannon** [comment]
Do you remember what version of vATIS you had prior to it wanting to update to beta 10?

**Comment by neilenns** [comment]
Beta 9

**Comment by justinshannon** [comment]
I can't reproduce this. Can you look in the vATIS Logs folder and see if there is an error log for when this happened? If so, can you upload it?

`%localappdata%\vATIS-4.0\Logs`

**Comment by neilenns** [comment]
I can but... I can't :( I'm now out of town until next week :(

**Comment by justinshannon** [comment]
No worries, just when you have time.

**Comment by neilenns** [comment]
[Log.txt](https://github.com/vatis-project/vatis/files/11391683/Log.txt)

Here you go!

**Comment by neilenns** [comment]
Unfortunately it doesn't look like there's anything useful in the logs from the 26th :(

**Comment by justinshannon** [comment]
I wonder if it was related to #132, specifically with regards to the silent updater not previously including the required .NET dependencies...

Let me know if you have issues updating to beta 12.

**Comment by neilenns** [comment]
Download of both 11 and 12 worked fine.
