### ISSUE TITLE
[BUG] - Minimizing causes weird behavior

### ISSUE THREAD

**Issue by Nikolai558** [vatis-project/vatis#13]
Minimizing and opening it up causes some unexpected behavior. See examples below: 

![image](https://user-images.githubusercontent.com/38259407/164059141-93850712-0b36-4f1d-9020-42c3f9d706e2.png)
![image](https://user-images.githubusercontent.com/38259407/164059173-98dec4db-3f82-4577-9af4-1e923dc69cac.png)

Upon minimizing and opening it up a number of times, the display looks correct. 
![image](https://user-images.githubusercontent.com/38259407/164059279-24fc3aed-135f-41c4-ae81-cd0f5ab0765c.png)

I am not sure if this is just my computer or not but my specs are listed below.
Windows 10 Pro
AMD FX(tm)-6300 Six-Core Processor
16.0 GB RAM

**Comment by justinshannon** [comment]
I am unable to reproduce this on my end. It looks like a video driver rendering issue.
