### ISSUE TITLE
Pairs of runways by voice ATIS

### ISSUE THREAD

**Issue by goulven04** [vatis-project/vatis#131]
Hello,

In LFPG, we use pairs of departure and landing runways. 

Would it be possible to add a feature in order to handle something like: `LANDING RUNWAYS 08R AND 09L`? 

Today only `08R` would be translated to `08 RIGHT` and the only workaround is to use `LANDING RUNWAY 08R AND RUNWAY 09L`

Thank you!

**Comment by justinshannon** [comment]
This is not currently possible. You can, however, create a Contraction for `LANDING RUNWAYS 08R AND 09L` with a spoken string of `LANDING RUNWAY ZERO EIGHT RIGHT AND RUNWAY ZERO NINER LEFT`.

**Comment by neilenns** [comment]
I'd love to see support this as well. We land parallel runways all the time at KPDX and KSEA and can't get the voice ATIS to properly speak both runways when using phrasing like "ILS RWYS 10L & 10R IN USE".

Perhaps some sort of character in front of the second runway to force it to be spoken as a runway? E.g. `^10R` or something?

**Comment by justinshannon** [comment]
This is available in beta 13, appending a caret (e.g. `^10R`) to the runway identifier will force vATIS to speak the runway correctly.

**Comment by neilenns** [comment]
WOOOOOOOOOOOOOOOOOO!

**Comment by kengreim** [comment]
We run into this problem at SFO too with our parallels, thanks for the new formatting token!

**Comment by goulven04** [comment]
Thank you!
