### ISSUE TITLE
Error: METAR not found and disconnection of the ATIS

### ISSUE THREAD

**Issue by raihan777** [vatis-project/vatis#133]
Hi,

It is being noted that whenever the METAR is not found, the ATIS gets disconnected, rather than showing the last METAR data, any possibility to let it be connected with last available data until and new METAR is available?

**Comment by justinshannon** [comment]
Are you experiencing this frequently? If so, what airport(s)? 

It’s possible, but it’s a question of how long it should remain connected with the old METAR until a new one is available?

**Comment by raihan777** [comment]
I was positioned on OPKR_CTR and was using ATIS for OPKC - Jinnah International; the METAR was almost unavailable for 15 ~ 20 min, as soon as i got new METAR in ES, then I was able to connect vATIS for OPKC

About the frequency i am not sure, though before the last update, i was not able to connect to ATIS through vATIS as i was getting error no OPKC airport then i used the ES default ATIS option.

**Comment by raihan777** [comment]
thank you for the info, waiting for the update, good day

**Comment by justinshannon** [comment]
It's available now in beta 13.
