### ISSUE TITLE
Cloud altitude /// is 0ft instead of undetermined or below station level + omits convective type

### ISSUE THREAD

**Issue by Phil7789** [vatis-project/vatis#138]
With a cloud altitude of /// the spoken ATIS is "0ft" but should be "undetermined" or "below station level" instead. If a convective types follows the type is omitted.

e.g. FEW///TCU is spoken as "FEW clouds at 0" but should rather be e.g. "FEW clouds undetermined towering cumulus" and text could "FEW undetermined TCU"

Was 52184a2 an attempt to fix?

**Comment by justinshannon** [comment]
The next update will include two new formatting fields that will allow you to customize the text and voice string for an undetermined cloud layer altitude.

**Comment by Phil7789** [comment]
That is what I call a quick fix. Thank you very much. Now I need bad enough weather to test it, but it looks great :)

Btw the missing convective type was probably missing because {convective} is not default with FEW. Why this isn't default I don't know, I've added it and will also test it.

**Comment by justinshannon** [comment]
There was actually a bug in the METAR parsing that broke the convective type if the altitude was undetermined. It wouldn’t have worked even if you added the `{convective}` variable.
