### ISSUE TITLE
Weird Pronunciation of "ILS"

### ISSUE THREAD

**Issue by aturneruk** [vatis-project/vatis#139]
vATIS 4.0.0-beta.13

I've added "EXPECT AN ILS APPROACH" to my NOTAMS on vATIS and am getting strange pronunciation (see attached recording) -- it sounds almost like "IELS".

https://github.com/vatis-project/vatis/assets/2829581/629a71dc-06ba-4ad8-b0cd-36b65a35180c

**Comment by justinshannon** [comment]
This should be fixed in the latest beta.
