### ISSUE TITLE
[NAVDATA] ICAO identifier not found

### ISSUE THREAD

**Issue by NEAvACC** [vatis-project/vatis#14]
Hi, 

I believe vATIS still uses older set of navdata, I'm trying to add Khartoum ICAO:HSSK and Juba ICAO:HJJJ which were previously HSSS and HSSJ. 

![image](https://user-images.githubusercontent.com/80136591/164112829-9cc6a5d6-84ad-4bb3-acda-e6026333f488.png)

Any chance of updating the nav database to reflect those changes?

Thanks.

**Comment by NEAvACC** [comment]
Hi, any update on this matter, is seems that many ICAO codes were not updated in the new beta

**Comment by justinshannon** [comment]
@CaptainYukinoshitaHachiman If you can provide a list of missing identifiers and names, they can be added.
