### ISSUE TITLE
Static NOTAMS are sometimes copied over to Arpt cond

### ISSUE THREAD

**Issue by Phil7789** [vatis-project/vatis#140]
As mentioned static NOTAMS are sometimes copied over to the airport conditions and saved as static there as well. If an entry already exists in arpt cond this does not happen.
I couldn't reproduce when it happens but it seems to happen when copying composites and (maybe) after reloading the software. I'm pretty sure that I removed everything from arpt cond yesterday but my arpt conditions where filled again (not on every composite though)

**Comment by justinshannon** [comment]
This should be fixed in beta 14.
