### ISSUE TITLE
[Feature] Profile automatically defaults to international format

### ISSUE THREAD

**Issue by trismann** [vatis-project/vatis#15]
No longer possible to toggle between International/FAA formatting like in the previous version. Would be nice to bring back as the FAA formatting was more similar to the Canadian format compared to the International format provided within vATIS.

**Comment by AlexandruB30** [comment]
Im currently working on a simple fix! Hang tight!

- Alexandru Bangala 1343029 CZUL S3

**Comment by justinshannon** [comment]
An option will be available in the next version to use the FAA format if desired. If unchecked, the international/ICAO format will be used.
