### ISSUE TITLE
Unable to use the latest beta (Win7)

### ISSUE THREAD

**Issue by tgpetrica** [vatis-project/vatis#154]
Hello,

One of our controller tried to run vATIS and cannot use it because it shows an error. They are on Windows 7 (OS).

The log is attached below.
[Log.txt](https://github.com/vatis-project/vatis/files/11824306/Log.txt)

**Comment by justinshannon** [comment]
Windows 7 is not a supported operating system. https://docs.vatis.clowd.io/#/client?id=system-requirements
