### ISSUE TITLE
[BUG][Feature]Tab Inconsistency

### ISSUE THREAD

**Issue by dylandxt** [vatis-project/vatis#16]
The number of tabs can reaches 8 when adding more than 4 airport setups. But get cut to 4 when reloaded.

**Comment by dylandxt** [comment]
It might be intended, but I will request to have 8 tabs available. Controllers could choose which one to connect instead of multiple configurations.

**Comment by justinshannon** [comment]
vATIS is currently limited to 4 composites per profile during the testing period.

**Comment by dylandxt** [comment]
![More than 4 tabs](https://user-images.githubusercontent.com/99299646/164343877-98238d0c-54af-415a-8566-9d714dc8364d.png)
When adding files, the program can display more than 4 tabs. This probably is a bug but I would say it is better to keep it like that so the controller can choose what airport within the TRACON they can have ATIS on (for instance, a TRACON with 5 fields would need 4 different configuration files). I am not sure if the connection limit is on the VATSIM servers side or on the client side. If the server is limiting the connection, there is no point in limiting the number of tabs you can have.

**Comment by justinshannon** [comment]
The next version will allow up to 15 composites defined in a single profile, but still limited to 4 simultaneous ATIS connections.
