### ISSUE TITLE
ATIS recording not reading runways correctly. 

### ISSUE THREAD

**Issue by Awemeter** [vatis-project/vatis#164]
Atis at KLAX:
KLAX ATIS INFO F 0353Z. 24011KT 10SM OVC032 20/16 A2997 (TWO
NINER NINER SEVEN). SIMUL INST APCHS AND RNAV RNP RWYS 24R AND
25L APCHS, AND SIMUL APCHS IN PROG BTWN LAX AND HHR, SIMUL INSTR
DEPARTURES IN PROG RWYS 24 AND 25. NOTAMS... ASDE-X SYSTEM IN
USE. ACTIVATE TRANSPONDER WITH MODE C ON ALL TWYS AND RWYS.
READBACK ALL RWY HOLD SHORT INSTRUCTIONS. ...ADVS YOU HAVE INFO
F

Instead of the ATIS reading two four right and two five left it reads 24 right and two fivelebel. The first runway sounds fine but the second one gets read weirdly.

**Comment by dillten** [comment]
Same issue just cropped up in latest version.

ATIS: 
```KAUS ATIS INFO A 1653Z. 26705KT 10SM FEW060 FEW200 32/17 A3005 (THREE ZERO ZERO FIVE). ARRIVALS EXPECT VISUAL APPROACH RWY 36R 36L. DEPARTING RWY 36R 36L. SIMULAPP IN USE.. SQUAWK MODE CHARLIE ON ALL SURFACE AREAS...ADVS YOU HAVE INFO A```

Read: ```AUSTIN-BERGSTROM INT AIRPORT ATIS INFO ALPHA ONE SIX FIVE THREE ZULU. WIND TWO SIX SEVEN AT FIVE. VISIBILITY ONE ZERO.. FEW CLOUDS AT SIX THOUSAND, FEW CLOUDS AT TWO ZERO THOUSAND. TEMPERATURE THREE TWO. DEWPOINT ONE SEVEN. ALTIMETER THREE ZERO ZERO FIVE. ARRIVALS EXPECT VISUAL APPROACH RUNWAY THREE SIX RIGHT THREE SIXL. DEPARTING RUNWAY THREE SIX RIGHT THREE SIXL. SIMULTANEOUS APPROACHES IN USE. SQUAWK MODE CHARLIE ON ALL SURFACE AREASADVISE ON INITIAL CONTACT, YOU HAVE INFORMATION ALPHA```

**Comment by justinshannon** [comment]
Did you prefix the second runway identifier with a caret symbol (eg ^25L)?

**Comment by Awemeter** [comment]
> Did you prefix the second runway identifier with a caret symbol (eg ^25L)?

I don't know I was not the controller I was a pilot.

**Comment by dillten** [comment]
The caret fixes the issue. Thanks.

**Comment by Awemeter** [comment]
I just heard the issue again at KLAS. It reads 26L as 26L IXL and 1L as 1er. 

``KLAS ATIS INFO L 2256Z. 07010KT 10SM FEW200 BKN250 15/M11 A3008
(THREE ZERO ZERO EIGHT). VIS APPS IN USE RWYS 1L, AND 26L. LDG
RWYS 26L, 1L, AND 1R. DEPTG RWYS 1R FULL LENGTH, AND 1L AT TWY
*B. SIMUL APPS TO CROSSING AND PARALLEL RWYS IN USE. CONVERGING
RWY OPS IN EFFECT. NOTAMS... LAS VEGAS METROPLEX PROCEDURES IN
EFFECT. VERIFY NAVIGATIONAL DATA IS UP TO DATE. ASDE-X SYSTEM IN
USE. ACTIVATE TRANSPONDER WITH MODE C ON ALL TWYS AND RWYS.
READBACK ALL RWY HOLD SHORT INSTRUCTIONS. ...ADVS YOU HAVE INFO
L``
