### ISSUE TITLE
[Feature Request] Custom middle part of login & more than 2 ATISes per airport

### ISSUE THREAD

**Issue by capzDE** [vatis-project/vatis#166]
At the moment, vATIS only allows one combined ATIS (ICAO_ATIS) and/or a split departure and arrival ATIS (ICAO_D_ATIS and ICAO_A_ATIS). Would it possible to remove this restriction in order to a) allow for more than two/three ATISes per airport and b) customize the middle part of the login. This would allow us to accommodate more varied types of ATISes and similar broadcasts like separate VFR ATISes, ATISes in different languages, glider ATISes informing of TMA sector configuration, etc.

**Comment by justinshannon** [comment]
Only three ATIS types are supported: combined, departure and arrival. There are no plans for additional ATIS types.
