### ISSUE TITLE
https://datis.clowd.io/ NOT WORKING

### ISSUE THREAD

**Issue by ujazishere** [vatis-project/vatis#190]
Unable to get DATIS from https://datis.clowd.io/

**Comment by justinshannon** [comment]
Can you be more specific? What error are you getting? Post a screenshot.

**Comment by ujazishere** [comment]
Nevermind. Works again. Wasn't able to get any datis on any airports. Now finally able to get it

**Comment by justinshannon** [comment]
Gotcha. Looking at the logs, it looks like the FAA did have a service outage, so that might be why.

**Comment by ujazishere** [comment]
Appreciate it. Are you the guys managing datis.clowd.io ?

**Comment by justinshannon** [comment]
Yes, I maintain datis.clowd.io. I’m not familiar with FAA flight status information, so I probably wouldn't be much help.
