### ISSUE TITLE
[BUG] Changing voice type while connected requires reconnecting

### ISSUE THREAD

**Issue by collink2451** [vatis-project/vatis#2]
If you change the voice type from text to speech to voice recorded or vice versa it does not change the state on the main page to the new mode until you disconnect and reconnect.

I am assuming this is a bug and not an intended feature.

**Comment by TheAlphaFlyer** [comment]
Not just voice type. Also seems to have the same problem when using preset text.

**Comment by justinshannon** [comment]
Changing the voice option will require the ATIS to be disconnected. The next version will disable the voice option in the settings if the ATIS is connected.

The next version will trigger a new ATIS to be generated if there are changes made to the airport conditions and/or NOTAMs and their respective preset/static text options.
