### ISSUE TITLE
[Feature/Suggestion] Add version number to JSON block sent to IDS

### ISSUE THREAD

**Issue by mgg4** [vatis-project/vatis#20]
I haven't fully researched the "Breaking Change" to the IDS POST format, but wonder if it could it be somewhat mitigated by adding a version field to the new POST JSON format?  This would allow the code on the IDS page to parse the JSON and then handle the v4 format differently than the prior format based on the presence and value of the Version object.

This would enable a smoother transition for the IDS code from v3 to v4.

![image](https://user-images.githubusercontent.com/440459/164166913-42d6aea5-a944-4d76-999a-0f4baaba022b.png)

**Comment by justinshannon** [comment]
A `Version` property (with a value of `4.0.0`) will be added to the next version.
