### ISSUE TITLE
[BUG] Weird Scaling

### ISSUE THREAD

**Issue by matteomassini** [vatis-project/vatis#21]
Window does not scale correctly, happens for settings as well.

![vATIS_Issue](https://user-images.githubusercontent.com/92981595/164202052-1e1b0e72-1457-49cd-925e-f9bda6eccb02.png)

**Comment by aselder** [comment]
happens to me as well.

**Comment by justinshannon** [comment]
This should be addressed by this fix (2b283f7568b1c734dff8026b1356a701c38c9ccb), which will be included in the next beta release.

In the interim, you can fix the scaling issue by changing the compatibility settings of the exe.

![DpiFix](https://user-images.githubusercontent.com/3221191/164374527-0712d43d-e2af-429b-8074-3093f6af3d86.png)

**Comment by justinshannon** [comment]
This should be addressed in the next version.
