### ISSUE TITLE
Frequency not correctly displayed on text ATIS

### ISSUE THREAD

**Issue by gvert27** [vatis-project/vatis#22]
Hello :)

unfortunately, frequencies inside the text ATIS, are not correctly displayed on German airports. As you can see below, the frequency (either directly in the preset or as APRT Condition) is correctly typed in as 123.275, however the output on the connected ATIS, shows 123275, without the dot.

The voice ATIS however, correctly reads "one-two-three DECIMAL two-seven-five".

![vatis](https://user-images.githubusercontent.com/104078369/164238415-0123cd89-8103-479f-b5cf-c95904e530e5.PNG)
![vatis2](https://user-images.githubusercontent.com/104078369/164238518-233779a6-07bc-4460-a201-b7d20dfc8354.png)

**Comment by justinshannon** [comment]
This will be fixed in the next version.
