### ISSUE TITLE
Display Numbers as Digits in text output

### ISSUE THREAD

**Issue by Frenkii** [vatis-project/vatis#25]
Any chance to output numbers as digits?

i.e. 
_TWO -> 2_ 

etc.

**Comment by justinshannon** [comment]
What section(s) of the ATIS would this apply to? Would it be for a non-US airport ATIS?

**Comment by Frenkii** [comment]
Correct!
Like this?

FRANKFURT INFORMATION W MET REPORT TIME 1050
EXPECT VECTORS FOR ILS APPROACH RUNWAY 07R OR ILS Y APPROACH
RUNWAY 07L RUNWAYS IN USE 07C 07L 07R AND 18 TRL 70
WIND 110 DEGREES 13 KNOTS VARIABLE BETWEEN 070 AND 130
DEGREES VISIBILITY 10 KILOMETERS CLOUDS SCATTERED 3800
FEET BROKEN 4300 FEET TEMPERATURE 15 DEW POINT 6 QNH
1004 TREND NOSIG FRANKFURT INFORMATION W OUT

**Comment by justinshannon** [comment]
This should be addressed in the next version. If it persists, please open a new issue and include the composite configuration file.
