### ISSUE TITLE
[BUG] Scaling Issues

### ISSUE THREAD

**Issue by wiggleforlife** [vatis-project/vatis#3]
#### Issue
The clock doesn't fit.
![image](https://user-images.githubusercontent.com/46230102/163912721-f362d774-9063-4c5e-89a1-e34f8b7e56d9.png)
The first composite doesn't fit in the Profile Configuration window.
![image](https://user-images.githubusercontent.com/46230102/163912794-99b2611c-3b2e-4dfe-9540-90cc9e881c1b.png)
The buttons in the New Preset dialogue don't fit.
![image](https://user-images.githubusercontent.com/46230102/163912840-6c35b9e0-877e-4386-a06d-bb89bc7e5566.png)
The ATIS template *seems* to not fit. This may not be a scaling issue, could be intentional. The same thing happens with the Configuration tab - the spacing seems a little tight at the bottom.
![image](https://user-images.githubusercontent.com/46230102/163912901-b94f6591-d298-4399-a43b-2c6a9a3f0e0f.png)
#### Display Specs
* 2560x1600
* ~137 DPI (according to an online calculator, not an official specsheet)
* 125% Scaling
* Win 10 Pro

**Comment by justinshannon** [comment]
Related to #21. To be resolved in the next beta.
