### ISSUE TITLE
vATIS should say "wind" instead of "surface wind" at non "K" USA airports

### ISSUE THREAD

**Issue by yancarlos4500** [vatis-project/vatis#30]
TJSJ which is an U.S. territory and an FAA airport, doesn't use the FAA format on the ATIS. Instead of saying "Wind" is says "Surface Wind". Also, SM is read as "Meters"

**Comment by justinshannon** [comment]
A config option will be added to the next version to force the composite to use the FAA ATIS format.

**Comment by justinshannon** [comment]
The real world D-ATIS text format for TJSJ follows the standard FAA format. Is the spoken ATIS different than what is written in the ACARS text?

Most recent RW D-ATIS:

> SJU ATIS INFO U 1656Z. 07006KT 10SM SCT016 BKN029 OVC045 26/24 A2999 (TWO NINER NINER NINER) RMK VCSH SE S. ILS AND VISUAL APCHS RWY 8 IN USE, 10 IN USE. DEPG RWY 8. NOTAMS... TWY C CLSD BTN TWY B AND TWY H, TWY H CLSD BTWN H 1 AND H 3. H 2 AND H 3 INTERSECTIONS CLSD. TWY N 1 CLSD. S INTERSECTION CLSD. EXPECT RWY 8 AT S 1 INTERSECTION DEPARTURE. USE CAUTION, BARRICADED AREA ON TWY H BETWEEN H 3 AND H 4. TACAN AZIMUTH OTS. BIRD ACTIVITY VICINITY ARPT. ALL RWYS AND TWYS WET. READBACK ALL RWY HOLD SHORT INSTRUCTIONS. FOR CPDLC USE K U S A. APRON 2 AND APRON 3 PUSHBACKS, START UP AND UNHOOK AT INTERMEDIATE HOLDING POSITION MARKING. ...ADVS YOU HAVE INFO U.

I need further clarification on your request for SJU. You're wanting the wind to be read as "surface wind..." and the visibility to be converted to metric?

**Comment by yancarlos4500** [comment]
I was probably drunk when I wrote that. You added the option to force the FAA format and it fixed the issue.
