### ISSUE TITLE
Missing leading "0" on non-US RWY Designators

### ISSUE THREAD

**Issue by gvert27** [vatis-project/vatis#31]
On non-US airports, the voice ATIS is missing the leading "0" for RWY designators. While in the US it is RWY 6 (Runway SIX) in Europe e.g. it is RWY 06 (ZERO-SIX).

[FACILITY] ATIS INFO [ATIS_CODE] MET REPORT TIME [OBS_TIME]. EXPECT ILS APPROACH RUNWAY 06. RUNWAY IN USE 06. ATTENTION! DEPARTURE FREQUENCY FOR ALL DEPARTING AIRCRAFT IS LANGEN RADAR ON 135.650 [TL]. [FULL_WX_STRING]. [FACILITY] INFORMATION [ATIS_LETTER] OUT.

**Comment by justinshannon** [comment]
This will be fixed in the next version.
