### ISSUE TITLE
2 ATIS updates via subscribe (vATIS 4.0 Beta)

### ISSUE THREAD

**Issue by svalencia014** [vatis-project/vatis#32]
When I subscribe to another controller's atis, I get 2 updates. One is new wind/altimeter with old atis code, then 15 seconds later it sends a 2nd one with the New Atis code and information.

Steps to reproduce:
Message the atis "subscribe" and either wait for an update or manually update the ATIS

I got this ATIS when I logged into Delivery, which was B and this was the ATIS update
![image](https://user-images.githubusercontent.com/68522351/166826105-2873cfce-68da-4a48-9a8e-6cc6027de2ac.png)

**Comment by svalencia014** [comment]
I'll try and get more examples of it as I keep controlling. Not the first time this has happened though.

**Comment by svalencia014** [comment]
![image](https://user-images.githubusercontent.com/68522351/168488913-cfa3c813-70d4-4aa4-9635-74ebfc3410d6.png)

**Comment by svalencia014** [comment]
![image](https://user-images.githubusercontent.com/68522351/172509084-49ee4295-c966-4cb4-adc7-8fc197521704.png)

**Comment by catcarbon** [comment]
This happens in beta 3 as well. 

Seems like when there's an automatic update, vATIS first notifies subscribers of the old ATIS. After the controller confirms the update vATIS will notify again of the new ATIS.

![subscribe](https://user-images.githubusercontent.com/9087266/177405349-b01c13e9-c716-49c5-8df4-72f0a7c27862.png)

**Comment by svalencia014** [comment]
![image](https://user-images.githubusercontent.com/68522351/178062960-eb0f420b-3f23-4a54-b98a-77510b561767.png)

**Comment by dylanm312** [comment]
I'm experiencing this issue as well.
