### ISSUE TITLE
Startup window doesn't render correctly on high resolution displays

### ISSUE THREAD

**Issue by neilenns** [vatis-project/vatis#34]
My machine is configured to run at 3456x2160 with 250% scaling at the OS level.

Result:

![image](https://user-images.githubusercontent.com/9524118/167035854-f143d97d-bebf-4d6d-84e5-d0edbe70314b.png)

Expected result:

Correct scaling of the UI.

I was able to work around the issue by applying the scaling override described here: https://github.com/vatis-project/vatis/issues/10, however the base app should hopefully handle this natively.

**Comment by justinshannon** [comment]
I don't have a high resolution monitor, so I cannot currently provide a resolution for this.

If I upgrade my monitor in the future, I will look into this. Until then, you'll have to apply the scaling override like you mentioned.
