### ISSUE TITLE
Frequencies ending in a .0

### ISSUE THREAD

**Issue by ml0130** [vatis-project/vatis#37]
For some reason, if there is a NOTAM with a frequency that ends in a .0 and no other trailing number it reads it as if it was a normal number. For example for Area 3 of SCT, I run a NOTAM `CLNC IS CLSD FOR CLNC CTC SO-CAL APP 127.0` but for some reason instead of it as one-two seven-point zero. It reads it as One Henered Twenty Seven.

Is this a known problem?

**Comment by amosngSP** [comment]
![image](https://user-images.githubusercontent.com/40349656/170296054-3b393044-d187-4b4b-8b26-3fa43f69be2d.png)
You need to disable "Format ATIS using FAA format" and "Use "decimal" terminology in spoken text"

**Comment by justinshannon** [comment]
This should be fixed in beta 3; please test and let me know.

**Comment by ml0130** [comment]
https://user-images.githubusercontent.com/27445711/175798829-b94cc9fa-8278-4380-9468-c9473fda51c0.mp4

@justinshannon can confirm that #48 is fix. but it does seem that the frequency issue could use some tweaking when they end in a 0. Ref the sound file
