### ISSUE TITLE
[Feature] Make composites a single reference for all profiles accessing it

### ISSUE THREAD

**Issue by collink2451** [vatis-project/vatis#4]
Hopefully there is a way to do this without breaking too much.
Basically, while thinking through our options at ZBW, the ideal environment would be to have a profile for each Tracon, then a Center profile with the most popular airports that may have an ATIS.
Because some facilities would be referenced in multiple profiles it would be nice if the composite information could be stored globally and referenced by ICAO in the individual profiles so when changed in one profile it would be reflected in any other profiles.

This change would make it much easier for FEs and considering it is still beta, if this change were to be made it should probably be done now before it has the potential to affect too many facilities.

**Comment by justinshannon** [comment]
Good point. What I think I'll do is create a separate tool that FE's can use to add, edit or delete individual composites all in one place. The tool would allow the FE to export one or more composites into a single vATIS Profile that can be imported by the end-user.

I'll probably still keep the Profile Configuration window in vATIS, but maybe hide it so it can only be opened using a keyboard combination so users don't get confused thinking they need to modify the settings.

**Comment by justinshannon** [comment]
A separate Profile Editor tool has been added in the next version.
