### ISSUE TITLE
Synthesized Voice Issues

### ISSUE THREAD

**Issue by catcarbon** [vatis-project/vatis#41]
### modifying config doesn't work 
 - Leading zero(es) in `[OBS_TIME]` is not read (e.g. `190251Z` is read as "two five one zulu").
 - `TODA` is read as "take-off distance", not as "take-off distance available". 
 - No pause between `[NOTAM]. ...ADVS YOU HAVE INFO...`.

### modifying config works
 - Runways with L/R/C designator aren't read correctly (e.g. `22L` sounded like "two twelve").
   -  Works if enclosed in braces (e.g. `{22L}` but braces are included in generated text).
 - No pause between `[ATIS_CODE] [OBS_TIME]`
   - Works if separated by a period.

Generated text:
```
KEWR ATIS INFO C. 0251Z. 21007KT 10SM SCT095 BKN130 OVC250 19/07
A2986 (TWO NINER EIGHT SIX). ILS RWY 22L APCH IN USE. DEPTG
RWY {22R} FROM INT *W, *10,150 FT TODA.. NOTAMS... OPERATE XPDR
ON MODE *C ON ALL TWYS AND RWYS. READBACK ALL RUNWAY HOLD SHORT
INSTRUCTIONS AND ASSIGNED ALT.. ...ADVS YOU HAVE INFO C.
```

Preset:
`[FACILITY] ATIS INFO. [ATIS_CODE]. [OBS_TIME]. [FULL_WX_STRING]. [ARPT_COND]. [NOTAMS]..`

Free text areas:
![image](https://user-images.githubusercontent.com/9087266/169202206-46808805-7d13-40df-bf41-3a3dfb647cab.png)

**Comment by catcarbon** [comment]
## Potential fixes on our end
### No pause between `[NOTAM]. ...ADVS YOU HAVE INFO...`.
- Change `"ArbitraryText": null` to `"ArbitraryText": ". "`?

**Comment by mythicfci** [comment]
I can confirm I'm having the same issue with vATIS not reading starting 0s, e.g., 0350 is read as "three five zero" rather than "zero three five zero."

**Comment by justinshannon** [comment]
These issues should be fixed in beta 3. Please test and let me know.

**Comment by catcarbon** [comment]
Thanks for the fix!
