### ISSUE TITLE
Beta 2 - Cannot make new composite if "Keep vATIS window visible" selected.

### ISSUE THREAD

**Issue by TheAlphaFlyer** [vatis-project/vatis#43]
Steps to reproduce:
- Open vATIS, any profile
- Select Keep vATIS window visible, save settings
- Go to manage profiles and press manage composite and make, edit, rename a composite

Outcome:
Window appears for 1 second, then disappears into background, and unable to reselect. Only fix is either via "enter" or "Alt + F4".

Expected Outcome:
Window to appear, clickable and accessible for editing/setup.

**Comment by ml0130** [comment]
@justinshannon I can confirm that this problem is also happening when adding a new ATIS Template.
