### ISSUE TITLE
[Feature Request] Show generated text for voice recorded ATIS without a recording

### ISSUE THREAD

**Issue by catcarbon** [vatis-project/vatis#46]
## Current behavior
For voice recorded ATIS, generated ATIS text doesn't show up in the communication panel unless there's a recording.

## Interim solution
Make a short recording.

## Requested feature
- Add a "use without recording" button to the record dialog, or
- Automatically transmit generated text upon connection (changes in airport condition and NOTAM will refresh text)

**Comment by justinshannon** [comment]
I'm not sure what you mean by "generated ATIS text doesn't show up in the communication panel". What panel are you referring to? Can you provide a screenshot?

**Comment by catcarbon** [comment]
When pilots/controllers click `Request ATIS` on the voice channel created by vATIS, they expect to get the generated text. However, beta.2 doesn't send the generated text to the voice channel unless there's a recording for voice-recorded ATISs. Thanks!

**Comment by justinshannon** [comment]
Disregard previous, I tagged the wrong issue.

**Comment by catcarbon** [comment]
Thank you!
