### ISSUE TITLE
[Feature Request] Code Range for Separate Departure/Arrival ATIS

### ISSUE THREAD

**Issue by catcarbon** [vatis-project/vatis#47]
Example: 
- `KATL_D_ATIS` auto update from Z will return to A, but departure ATIS range is N to Z
- `KATL_A_ATIS` auto update from M will go to N, but arrival ATIS range is A to M
- Controllers need to manually reset the ATIS letter according to SOP.

Requested:
Add a `CodeRange` property in `Composite` so that...
- `KATL_D_ATIS` auto update from Z will return to N (`"CodeRange": [N, Z]`)
- `KATL_A_ATIS` auto update from M will return to A (`"CodeRange": [A, M]`)

**Comment by justinshannon** [comment]
This will be available in the next version (not yet released).
