### ISSUE TITLE
[Bug] Runway Designations Not Synthesized Correctly

### ISSUE THREAD

**Issue by ml0130** [vatis-project/vatis#48]
https://user-images.githubusercontent.com/27445711/169677429-eb0b3be3-f3fb-48df-a19c-4259fe7c6b6d.mp4

Not exactly sure if this is a problem with vATIS or with the synthesized voices directly. But it seems that at least as of posting this issue the synthesized voices are having an issue reading and synthesizing runways with L/R/C delegations. Please reference the audio file that's attached to this issue for the problem.

**Comment by catcarbon** [comment]
See also #41

**Comment by dylanm312** [comment]
I'm having this issue as well. Instead of 28 LEFT and 28 RIGHT I get "TWO EIGHT UHL" and "TWO EIGHT UHRR" lmao

**Comment by justinshannon** [comment]
This issue should be fixed in beta 3. Please test and let me know.

**Comment by ml0130** [comment]
Will do
