### ISSUE TITLE
vATIS crashes when weather updates to the next revision

### ISSUE THREAD

**Issue by polyath3911** [vatis-project/vatis#50]
![error_message](https://user-images.githubusercontent.com/15104021/169730778-472f2843-6c21-43fc-ba86-1071b167c70d.png)
[AppExceptions.txt](https://github.com/vatis-project/vatis/files/8750839/AppExceptions.txt)

**Comment by michael-parry** [comment]
I've had this same problem, and I've also seen it mentioned on the VATSIM forums. Someone else in my ARTCC had this same problem as well.
