### ISSUE TITLE
How to use uniATIS - Missing Documentation

### ISSUE THREAD

**Issue by gvert27** [vatis-project/vatis#57]
Unfortunately the documentation regarding the use of uniATIS to create the ATIS, is a bit sparse. So far I haven't been successful to make the uniATIS link, the live ATIS. While it correctly fetches the ATIS via "Test URL", it doesn't do anything to the connected one.

Am I doing something wrong or missing something?

**Comment by justinshannon** [comment]
Documentation for using an external ATIS generator has been added to the documentation: https://docs.vatis.clowd.io/#/client?id=presets
