### ISSUE TITLE
[Bug/Feature Request] Prepending "wind" instead of "surface wind"

### ISSUE THREAD

**Issue by mythicfci** [vatis-project/vatis#59]
At the moment, there is only one option in Formatting to "Prepend 'surface wind' to spoken wind." When this option is disabled, vATIS only reads out the wind itself, e.g., "300 degrees 20 knots" instead of "surface wind 300 degrees 20 knots."

This is awkward for those of us who want to make vATIS profiles which say "wind 300 degrees 20 knots," because it means we have to manually add the word "wind" in front of the WX string, e.g. `WIND [FULL_WX_STRING]`. This means that the text output of the ATIS becomes weirdly formatted, as you end up just having the word "WIND" in front of a long METAR string, like this:
![image](https://user-images.githubusercontent.com/49729038/171051883-16db1da9-5feb-48c2-8022-3e52b565f71e.png)

(Note: this screenshot also shows bug #42 where unticking the "Prepend 'surface wind' to spoken wind" option makes the winds invisible in the text ATIS)

I'm not sure if unticking the option "Prepend 'surface wind' to spoken wind" is intended to completely remove any prefix from the spoken wind, so I don't know if this is a bug or a feature request. However, for those of us trying to generate ATISes with the word "wind" before the spoken wind, it would be a significant help if we could specifically have an option to prepend "wind" _instead of_ surface wind, rather than just having the option be between prepending "wind" and prepending nothing.

**Comment by justinshannon** [comment]
This should be fixed in beta 3.
