### ISSUE TITLE
[Feature] Connect more than 1 atis to 1 facility

### ISSUE THREAD

**Issue by TheAlphaFlyer** [vatis-project/vatis#6]
Hi,

I recently checked with Matt Bozwood-Davies - 1240411 in the VATSIM Community Discord and the temporary trail allows the use of multiple atis for one airport. Will you be able to fix this so airports that do use a seperate atis for dep and arr can be replicated?

Thanks

**Comment by TheAlphaFlyer** [comment]
ATIS also only allows FACLITY_ATIS. Rather than individual callsigns like FACILITY_D_ATIS or FACILITY_A_ATIS

**Comment by justinshannon** [comment]
Departure and Arrival ATIS support will be made available in the next version.
