### ISSUE TITLE
Text ATIS when using external generator

### ISSUE THREAD

**Issue by laxentis** [vatis-project/vatis#62]
When you enable the external generator, the preset text area becomes inactive:
![obraz](https://user-images.githubusercontent.com/744494/173176244-05fee8c3-c5b6-469f-9a69-016bb28fb27f.png)
That causes the text ATIS to be non-editable in the GUI and results in the following text ATIS:
![obraz](https://user-images.githubusercontent.com/744494/173176280-49be9cdc-f6cb-4528-bbdc-59a48b4a819a.png)
that is pretty incomplete for an ATIS.

**Comment by troe2339** [comment]
I am having the same issue. It'd be great if it would "simply" be the text from the test url box that functions as the text ATIS.

**Comment by justinshannon** [comment]
This is by design. If the composite is configured to use an external ATIS generator source (i.e. UniATIS), then the external source defines the ATIS template format.

**Comment by amosngSP** [comment]
> This is by design. If the composite is configured to use an external ATIS generator source (i.e. UniATIS), then the external source defines the ATIS template format.

Yep but the text ATIS shown does not reflect what is being generated by the external ATIS source. It's only the voice ATIS that reflects it correctly.

**Comment by RudiZhang** [comment]
@justinshannon Simply understood as the difference between D-ATIS and Voice ATIS, D-ATIS include text message in Abbreviations and voice in full

**Comment by Iwhite67** [comment]
same here 
![image](https://user-images.githubusercontent.com/9698964/182666822-2eb3004c-8461-4f06-be5a-fdbb57560cdd.png)
![image](https://user-images.githubusercontent.com/9698964/182666857-95067bec-c5c1-43f0-be75-42da52a4b120.png)

**Comment by ThaweK** [comment]
Yes, Voice does not correspond to whats "External ATIS Generator" spits out.

**Comment by fagidutt** [comment]
bump. same issue, if i use the external atis generator, the voice atis is received according to the atis generated by the external source, which is to be expected.

in the text atis, fed to vatspy, etc., however, there will be only the above mentioned shortened, undecoded atis/metar string, when normally, the atis string extracted from the external source would be expected to be output as text atis aswell.

in fact, if i change the preset template to another atis text, and then switch on the generate from external source option afterwards, the voice atis will, again be the one from the external source, whereas the text atis will remain the way it was defined in the preset template, this does not seem to be the intended behaviour, indeed.

even though it is at least via a loophole possible to influence the outcome of the text atis (by pre-setting the profile template), i would understand that the idea is to not have to define a text atis template in vatis anymore, if i use the external source, or is this a misunderstanding?
