### ISSUE TITLE
Dialog opens behind main display (v4 b2)

### ISSUE THREAD

**Issue by drchuck59** [vatis-project/vatis#63]
To reproduce:
Open ATIS v4 beta 2
Open any profile
Click "Manage Profiles"
Highlight a composite
Click "Manage Composite..."
-- Resulting modal dialog spawns behind Profile Configuration dialog
-- Modal dialog is not registered as its own window and cannot be alt-tabbed.
Recovery: Force-close application and restart

Chuck 1429208
fe@zjxartcc.org

**Comment by justinshannon** [comment]
I wasn't able to reproduce this. Can you try beta 3 and let me know if this is still happening?

**Comment by drchuck59** [comment]
No  longer occuring in beta 4
