### ISSUE TITLE
No wind in [full_wx_string]

### ISSUE THREAD

**Issue by troe2339** [vatis-project/vatis#64]
The wind is not showing up in the METAR part of the ATIS when I use [full_wx_string]. Neither is the "automatic weather report" part, but that's less important.

![image](https://user-images.githubusercontent.com/107309545/173896132-352e89a7-0be2-4815-ae4c-6e872d14cbe5.png)

![image](https://user-images.githubusercontent.com/107309545/173896314-f0822227-3284-433f-8a94-c70c0f1575e0.png)

![image](https://user-images.githubusercontent.com/107309545/173896222-089785ec-2dc9-42b9-b339-3ba9ba3b0452.png)

**Comment by mythicfci** [comment]
#42

**Comment by justinshannon** [comment]
Beta 3 should address this.

**Comment by troe2339** [comment]
Seems to be working so far in beta 3
