### ISSUE TITLE
[Error 10054] Remote Host

### ISSUE THREAD

**Issue by ml0130** [vatis-project/vatis#65]
I know we have seen similar Remote Host closures in the past vATIS versions. Just wanna make sure that this isn't a new one.

![image](https://user-images.githubusercontent.com/27445711/175803543-eeb6a9f7-036e-420c-a26c-995a2a768492.png)

**Comment by collink2451** [comment]
That is an issue between vATIS and the vatsim servers and not directly related with vATIS or Vatsim
