### ISSUE TITLE
[BUG] Transition Level

### ISSUE THREAD

**Issue by TheAlphaFlyer** [vatis-project/vatis#7]
In the profile configuration, I'm unable to save any changes made to the QNH Low/High/Level. It applies, but when i open it back up, it's empty.

**Comment by justinshannon** [comment]
I am unable to reproduce this. What value(s) are you inputting in the TL table?

**Comment by TheAlphaFlyer** [comment]
I am inputting 110 and 120

**Comment by TheAlphaFlyer** [comment]
Table exact info looks like this:

       | 980|110
979 |       | 120

**Comment by justinshannon** [comment]
A low and high QNH value is required for each transition level.
