### ISSUE TITLE
separate wind & without Q in QNH

### ISSUE THREAD

**Issue by RudiZhang** [vatis-project/vatis#73]
can you separate wind direction, wind speed and wind vary into 3 value? so user could motify in different format, like "WIND 340 DEG 05 KT" or "W 340 05 KT" or "34005KT"
![image](https://user-images.githubusercontent.com/40914896/183311357-a7403283-fd8e-4dce-a5b4-06db808715e0.png)

and also in ICAO ATISes, Q is not including in QNH

![image](https://user-images.githubusercontent.com/40914896/183304689-f579a48d-650f-45e9-ae1b-c5979c1e022f.png)
![image](https://user-images.githubusercontent.com/40914896/183304807-1e5dc5cd-00a3-429e-a90d-face6e4eee35.png)
![image](https://user-images.githubusercontent.com/40914896/183304813-f803017b-7c2f-4aeb-b7e2-1214cc84b31b.png)

**Comment by justinshannon** [comment]
@RudiZhang I've started the initial work on ATIS format customization, which will allow you to customize the voice and text output of each weather node in the ATIS (observation time, wind, visibility, RVR, present weather, clouds, temperature, dewpoint, altimeter, trends).

This will allow you to customize the wind text ATIS and voice readout, as you requested. The `{wind_spd}` and `{wind_gust}` can be optionally converted to a different unit type (i.e. kt to mps): `{wind_spd|mps}` `{wind_gust|kt}`

Presently, the config file will look something like this (subject to change of course). There will also be a UI to edit the ATIS format, but I haven't designed that yet.

```json
"NodeFormat": {
  "SurfaceWind": {
    "CalmWindSpeed": 2,
    "Voice": {
      "Standard": "WIND {wind_dir} AT {wind_spd}",
      "StandardGust": "WIND {wind_dir} AT {wind_spd} GUSTS {wind_gust}",
      "Variable": "WIND VARIABLE AT {wind_spd}",
      "VariableGust": "WIND VARIABLE AT {wind_spd} GUSTS {wind_gust}",
      "VariableDirection": "WIND VARIABLE BETWEEN {wind_vmin} AND {wind_vmax}",
      "Calm": "WIND CALM"
    },
    "Text": {
      "Standard": "{wind_dir}{wind_spd}KT",
      "StandardGust": "{wind_dir}{wind_spd}G{wind_gust}KT",
      "Variable": "VRB{wind_spd}KT",
      "VariableGust": "VRB{wind_spd}G{wind_gust}KT",
      "VariableDirection": "{wind_vmin}V{wind_vmax}",
      "Calm": "{wind}"
    }
  },
  "Temperature": {
    "PlusPrefix": false,
    "PronounceLeadingZero": false,
    "Text": "{temp}",
    "Voice": "TEMPERATURE {temp}"
  },
  "Dewpoint": {
    "PlusPrefix": false,
    "PronounceLeadingZero": false,
    "Text": "{dew}",
    "Voice": "DEWPOINT {dew}"
  }
},
```

**Comment by RudiZhang** [comment]
> 

That's Amazing! Thanks!

**Comment by justinshannon** [comment]
Beta 8 is available, which implements the new custom ATIS formatting. See the updated documentation for details on how to customize your ATIS format: https://docs.vatis.clowd.io/#/client?id=formatting
