### ISSUE TITLE
wind always in kt, didn't change to mps

### ISSUE THREAD

**Issue by RudiZhang** [vatis-project/vatis#74]
![image](https://user-images.githubusercontent.com/40914896/183311207-88551363-0c18-4d9d-9244-78ac30c39940.png)
![image](https://user-images.githubusercontent.com/40914896/183311211-fb6b7d4c-a42e-4125-8b9d-21ba8e3bf0f0.png)

**Comment by RudiZhang** [comment]
un update: if METAR was with gusting like 22006G12MPS it will be " 22006G12METERPERSECOND "
if just 22006MPS it will be "22006KT"

**Comment by justinshannon** [comment]
This should be fixed in the next version (not yet released).
