### ISSUE TITLE
upload voice file possible?

### ISSUE THREAD

**Issue by RudiZhang** [vatis-project/vatis#75]
like China, we use dual languages, add this option allow me to generate mp3

**Comment by justinshannon** [comment]
I'm not sure what you mean by this. Are you wanting to upload an automated voice file that's spoken in Chinese?

**Comment by RudiZhang** [comment]
@justinshannon For example, I am using local TTS to generate an mp3 that can be played directly through vATIS. This allows for a custom mechanical voice and of course two languages

**Comment by justinshannon** [comment]
vATIS will only support a single audio source, derived from the vATIS TTS server. It would be too complex to support multiple audio streams.
