### ISSUE TITLE
[Feature request] Manual WX entry

### ISSUE THREAD

**Issue by megazloj** [vatis-project/vatis#76]
Hello!
Here in Ukraine we don't have any weather stations running currently due to well-known events. It would be amazing if you add an ability to manually enter weather info (in METAR format) to provide ATIS for the pilots at the airport(s) where we're controlling.

**Comment by RudiZhang** [comment]
yeah agree, same in China, we have some METAR which not publish to VATSIM, for now, if there is no METAR, you can't even use vATIS to connect. I think the good idea is make an option, fully manuel.

**Comment by RudiZhang** [comment]
and i think in this case, add an option as "Manual ATIS code" will be great!
