### ISSUE TITLE
Keep on top not working on minimal view

### ISSUE THREAD

**Issue by rffuret** [vatis-project/vatis#79]
Seems like when using the minimal view (the one with only the letters), the setting to "Keep vATIS window visible" does not work

**Comment by justinshannon** [comment]
Can you confirm which version of vATIS you're using?

**Comment by rffuret** [comment]
Hey, 4.0.0-beta.3

**Comment by nozzrangar** [comment]
Same thing happening to me on 4.0.0-beta.3

**Comment by justinshannon** [comment]
This will be fixed in the next release (031e3d4).
