### ISSUE TITLE
IDS Update Issues

### ISSUE THREAD

**Issue by collink2451** [vatis-project/vatis#81]
For a while we (ZBW) have been having issues with our IDS not updating or even receiving all of the IDS update calls. Our server logs often do not show any of the requests even reaching the server yet if I use something like PostMan or the old vATIS it works every time. I did some digging and if only 1 ATIS composite is connected it will update correctly but if multiple are connected only 1 or none of the requests will reach the server.

If I manually update 2 of them within 1 second of each other the first request always shows up while the second one does not.

I have a feeling that there is an issue with the cancelation token being canceled by subsequent updates resulting in a TaskCanceledException that is thrown out here https://github.com/vatis-project/vatis/blob/main/Vatis.Client/Atis/AtisBuilder.cs#L509

There used to be a PostIdsUpdate error that caused an unhandled exception before that TaskCanceledException catch was added so now those extra requests are being thrown out without the user being informed.

At this point I can not build a version of vATIS to test on the network to do any further debugging but there is definitely an issue here that needs to be fixed. If you want to collaborate on this issue send me a PM on discord.

**Comment by justinshannon** [comment]
I think this should be fixed in beta 4 (just released). If you're still having issues, please re-open this issue and I'll investigate further.
