### ISSUE TITLE
[Feature] Option to add a short label name to the Airport Condition

### ISSUE THREAD

**Issue by fcooper94** [vatis-project/vatis#86]
![image](https://user-images.githubusercontent.com/16825107/206017132-239497d8-ce3a-4291-a7f2-bceb0ac83262.png)

DEPARTING AIRCRAFT MAKE INITIAL CONTACT WITH LONDON CONTROL 129.425
DEPARTING AIRCRAFT MAKE INITIAL CONTACT WITH LONDON CONTROL 134.125

As you can see the only bit I care about is the freq at the end, but it is hidden by the width restriction of the form.
Can we have a 'label' or 'short name' to summarise these labels? 

Therefore I can call one 'Contact 129.425' with the above longer string. etc

Many Thanks,
Fraser

**Comment by justinshannon** [comment]
This will be available in the next version (not yet released).
