### ISSUE TITLE
How to get current version?

### ISSUE THREAD

**Issue by cptalpdeniz** [vatis-project/vatis#87]
Hello, I'm developing a program in C# that checks the installed version of vATIS and was wondering is there a website or API or to be honest any way to get the latest version? I can check it from github releases but that requires DOM manipulation (maybe there is a way to get the latest version using `git` however I'm not that familiar and need to check it first). Any suggestions?

Thanks,
Alp Deniz Senyurt
ACCTR5

**Comment by cptalpdeniz** [comment]
@justinshannon @collink2451

**Comment by justinshannon** [comment]
vATIS uses this endpoint to check for the current version, which you're welcome to use: https://vatis.clowd.io/api/v4/VersionCheck

Note: Although I have no plans to actually do it, the URL or response format could change in the future without notice.

**Comment by cptalpdeniz** [comment]
Thank you very much for the prompt reply Justin! I'll try to monitor the URL and response and if it changes in the future (hopefully not), will make necessary updates. Appreciated.
