### ISSUE TITLE
CAVOK not being displayed

### ISSUE THREAD

**Issue by GGChief** [vatis-project/vatis#91]
CAVOK not shown on ATIS information despite being in the metar:

<img width="1003" alt="Screen Shot 2023-01-02 at 22 19 08" src="https://user-images.githubusercontent.com/66843302/212464521-88ac628d-e9af-4631-9c64-9da38cc0e361.png">
<img width="558" alt="Screen Shot 2023-01-02 at 22 19 04" src="https://user-images.githubusercontent.com/66843302/212464523-dbbbe76e-39cf-4b5a-9a46-e0c92d25ef0d.png">

**Comment by justinshannon** [comment]
This should be fixed in the next version (not yet released).
