### ISSUE TITLE
Any way to test/develop the app without getting a client auth error?

### ISSUE THREAD

**Issue by GGChief** [vatis-project/vatis#92]
Question is pretty self explanatory, I'm attempting to fix the CAVOK issue which I've opened in another thread but unable to test any changes due to client authentication. Is there any way to test the application without breaking the handshake?

**Comment by cptalpdeniz** [comment]
Where does this error happen? What are you doing at that time? Does it happen at compile or runtime? Can you give more details?

**Comment by GGChief** [comment]
> Where does this error happen? What are you doing at that time? Does it happen at compile or runtime? Can you give more details?

The compiling phase is fine, everything works without any issue and the app works. It's when I try to connect to thr network to see if my changes work, the client authentication fails. I understand that this is a security measure but how else would I be able to test the ATIS output?

**Comment by CPU-Blanc** [comment]
Same issue here...
I just played with switching the VATSIM local password encryption method over so that it can run in Linux via Wine (the current method just causes it to crash), and got the app to finally run. Only to be met with the "Unauthorized client software" error when trying to connect. Shame

**Comment by sparrowhe** [comment]
> > Where does this error happen? What are you doing at that time? Does it happen at compile or runtime? Can you give more details?
> 
> The compiling phase is fine, everything works without any issue and the app works. It's when I try to connect to thr network to see if my changes work, the client authentication fails. I understand that this is a security measure but how else would I be able to test the ATIS output?

I have the same problem, so I asked the project owner. They told me that there are some restrictions from VATSIM, and we cannot use non-official builds to connect to the network. So there's no way to have a online test :(

**Comment by justinshannon** [comment]
Unfortunately any sort of "online testing" isn't possible right now. Maybe in the future I can add support for some sort of local testing, but for now, it's not possible.
