### ISSUE TITLE
TREND Part of METAR

### ISSUE THREAD

**Issue by AUAA320** [vatis-project/vatis#93]
Is there any Variable to add the TREND-Part of European METARs into a vATIS generated ATIS?

For example:

EDDF 062050Z AUTO 05011KT 9999 SCT031 02/M02 Q1038 **BECMG 05006KT**

or

EDDM 062050Z AUTO 07005KT 9999 FEW018 M03/M06 Q1036 **NOSIG**.

This would be rather significant for European ATIS'.

**Comment by justinshannon** [comment]
TREND will be available in the next version (not yet released) using the `[TREND]` or `$TREND` variable in the ATIS template.
