### ISSUE TITLE
v-Atis would not load on windows 8.1pro

### ISSUE THREAD

**Issue by axeenah** [vatis-project/vatis#95]
Greetings,
I installed the latest v-atis 4.00 beta on my system which is 32 bit, but when I tried to run it windows complain that this program will not run on this computer. As if i have installed the 64 bit version of the program.

**Comment by justinshannon** [comment]
vATIS requires Windows 10 (or newer).

**Comment by axeenah** [comment]
vATIS was working fine on my other desktop that is running windows 8.1 with no issues.

**Comment by axeenah** [comment]
The only difference between the two pcs is that the other pc is on 64bit system

**Comment by axeenah** [comment]
Is there a 32bit version of vATIS please?

**Comment by justinshannon** [comment]
As Collin mentioned, only 64-bit Windows is supported. Sorry.
