### ISSUE TITLE
Removing QNH Prefix on PRESSURE_INHG and PRESSURE_HPA

### ISSUE THREAD

**Issue by mythicfci** [vatis-project/vatis#98]
@justinshannon Thanks for looking into #71!

Unfortunately, the feature as added isn't great for the purpose originally described in #71, since both `[PRESSURE_INHG]` and `[PRESSURE_HPA]` generate the prefix "QNH."

E.g., if I were trying to make an ATIS with both the hPa values and the InHg values (like the one in the recording from my original post) using the syntax `[PRESSURE_HPA] HECTOPASCALS, [PRESSURE_INHG] INCHES`, it ends up generating text like "QNH 1013 HECTOPASCALS, QNH 29.92 INCHES."

Is there a way to optionally _remove_ the QNH prefix (e.g., in the same way that appending "surface wind" is an option that can be turned off) in order to fix this? The intention is to make an ATIS where I can use the syntax `QNH [PRESSURE_HPA], [PRESSURE_INHG]` to produce text like "QNH 1013 HECTOPASCALS, 29.92 INCHES."

**Comment by justinshannon** [comment]
Hi @mythicfci,

Thanks for for your feedback. Would you mind giving this version a try? https://vatis.clowd.io/files/vATIS-Setup-4.0.0-beta.6+0c6d58d.exe

The `[PRESSURE_HPA]` and `[PRESSURE_INHG]` will _only_ return the converted pressure value. This way, you can define `QNH [PRESSURE_HPA] HECTOPASCALS, [PRESSURE_INHG] INCHES` in your ATIS template.

Let me know your results, and if this change will suffice your needs.

**Comment by mythicfci** [comment]
Hi @justinshannon, that version works much better in this respect — thank you so much!

**Comment by justinshannon** [comment]
Excellent, this will included in the next release.
